/**
 * Two-model external review of the prompt layer.
 *
 * Runs Codex (gpt-5.6-luna) and the Claude CLI (Opus) read-only over prompts/
 * plus the four direction docs, and writes both critiques to
 * docs/prompt-critique-<date>.md. Findings BOTH models raise independently are
 * the ones worth acting on; a finding only one raises is a hypothesis.
 *
 *   cd api && pnpm exec tsx --env-file=.env scripts/prompt-critique.mts [--only codex|claude]
 *
 * Costs one CLI call per model per run. Neither reviewer can write: codex runs
 * with --sandbox read-only, and claude is called in single-shot print mode.
 */
import { execa } from 'execa';
import path from 'node:path';
import { mkdir, writeFile } from 'node:fs/promises';
import { loadConfig } from '../src/config.js';

const REVIEW_TARGETS = [
  'prompts/story.system.md',
  'prompts/story.user.md',
  'prompts/topics.system.md',
  'prompts/topics.user.md',
  'prompts/story.change-request.md',
  'docs/visual-style.md',
  'docs/hook-improvement-plan.md',
  'docs/fal-video-generation.md',
  'docs/pipeline-learnings.md',
  'shared/src/craft.ts',
  'shared/src/slop.ts',
  'api/src/utils/storyValidate.ts',
];

const RUBRIC = `You are a ruthless short-form-video creative director and prompt engineer. Read these files (read-only, change nothing):

${REVIEW_TARGETS.map((f) => `- ${f}`).join('\n')}

Context: an automated pipeline writes 60-80s vertical "true WTF" micro-documentaries for TikTok/Reels. An LLM fills a JSON schema; TTS reads the narration; Gemini generates stills from image_prompt; fal image-to-video animates them from motion_prompt; Remotion burns an overlay layer and kinetic captions. docs/visual-style.md is the ROOT visual identity and outranks the other docs where they conflict.

Answer these, specifically, quoting file lines. No praise, no hedging, no closing summary:

1. AI SLOP. Which instructions will still reliably push the model toward generic "AI documentary voiceover" output? The prompt no longer contains literal example sentences (they rotate in from HOOK_EXAMPLE_POOL in shared/src/craft.ts) — so look for structural causes instead: beat-role labels that imply a plot template, rules that force even cadence, lists the model will treat as a menu to exhaust.

2. WHAT THE VALIDATOR CANNOT SEE. api/src/utils/storyValidate.ts holds every mechanical rule. Name the quality failures that would pass all of it. Those are the gaps that matter.

3. HOOK PORTFOLIO. Seven forms are defined. Is the set right? Which form will the model over-pick, and which will it fake?

4. EVIDENCE FILE FIDELITY. Judge the STYLE section and the era-to-capture-medium table against docs/visual-style.md. Where can a story satisfy the letter and miss the identity?

5. CONTRADICTIONS between the prompt files, the shared craft data, and the validator rules. Anything the model cannot simultaneously satisfy.

6. CONCRETE EDITS. Exact replacement lines for the weakest sections, preserving the hard rules (numbers as words, no digits, no bracketed tags, motion-only prompts, byte-identical style prefix injected server-side, 2-3 camera_locked beats, exactly one capture medium).

7. NEW MECHANICAL RULES worth adding to storyValidate.ts: the rule, the deterministic check, and error vs warning.`;

const args = process.argv.slice(2);
const only = args.includes('--only') ? args[args.indexOf('--only') + 1] : null;
const config = loadConfig();
const repoRoot = path.resolve(process.cwd(), '..');
const outDir = path.join(repoRoot, 'docs');
const stamp = new Date().toISOString().slice(0, 10);

async function runCodex(): Promise<string> {
  const { stdout } = await execa(
    config.codexCliPath,
    [
      'exec',
      '--skip-git-repo-check',
      '--sandbox', 'read-only',
      '--color', 'never',
      '--model', config.codexModel,
      RUBRIC,
    ],
    // stdin MUST be closed: codex exec waits for EOF on a piped stdin and
    // hangs forever before ever contacting the API
    { cwd: repoRoot, timeout: 1_800_000, stdin: 'ignore' },
  );
  return stdout;
}

async function runClaude(): Promise<string> {
  const { stdout } = await execa(
    config.claudeCliPath,
    ['-p', RUBRIC, '--output-format', 'json', '--model', config.claudeModel],
    { cwd: repoRoot, timeout: 1_800_000 },
  );
  const envelope = JSON.parse(stdout) as { result?: string; total_cost_usd?: number };
  return `${envelope.result ?? ''}\n\n_cost: $${envelope.total_cost_usd?.toFixed(4) ?? '?'}_`;
}

const reviewers: Array<{ name: string; model: string; run: () => Promise<string> }> = [
  { name: 'codex', model: config.codexModel, run: runCodex },
  { name: 'claude', model: config.claudeModel, run: runClaude },
].filter((r) => !only || r.name === only);

await mkdir(outDir, { recursive: true });
const sections: string[] = [
  `# Prompt critique — ${stamp}`,
  '',
  `Generated by \`api/scripts/prompt-critique.mts\`. Both reviewers ran read-only.`,
  `Treat a finding raised by only one model as a hypothesis; act on what both raise.`,
  '',
];

for (const reviewer of reviewers) {
  process.stdout.write(`\n[${reviewer.name}] ${reviewer.model} reviewing…\n`);
  const startedAt = Date.now();
  try {
    const body = await reviewer.run();
    sections.push(`## ${reviewer.name} · ${reviewer.model}`, '', body, '');
    console.log(`  done in ${((Date.now() - startedAt) / 1000).toFixed(0)}s`);
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    sections.push(`## ${reviewer.name} · ${reviewer.model}`, '', `**Failed:** ${message}`, '');
    console.error(`  failed: ${message.slice(0, 200)}`);
  }
}

const outPath = path.join(outDir, `prompt-critique-${stamp}.md`);
await writeFile(outPath, sections.join('\n'));
console.log(`\nWrote ${path.relative(repoRoot, outPath)}`);
